name: cstclub
description: "cstclub web application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2
  webview_flutter: ^4.8.0
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/cst_logo.png
    - assets/images/cstloadinglogo1.gif


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cst_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/cst_logo.png
  android: true
  ios: true

